### ISSUE TITLE
@AWS.RDS.DBSubnetGroup causes "has no method 'DBSubnetGroup'"

### ISSUE THREAD

**Issue by sithu** [chrisfjones/coffin#13]
Hi, 

I'm getting this error when creating RDS DB SubnetGroup:

undefined:111
    this.AWS.RDS.DBSubnetGroup('MyRDSDBSubnetGroup', {
                 ^
TypeError: Object #<Object> has no method 'DBSubnetGroup'
    at CloudFormationTemplateContext.eval (eval at <anonymous> (/usr/local/lib/node_modules/coffin/lib/command.js:78:33), <anonymous>:111:18)
    at module.exports (/usr/local/lib/node_modules/coffin/lib/coffin.js:314:10)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/coffin/lib/command.js:78:33), <anonymous>:2:27)
    at /usr/local/lib/node_modules/coffin/lib/command.js:78:18
    at fs.js:252:14
    at Object.oncomplete (fs.js:93:15)
###### # CoffeeScript

@AWS.RDS.DBSubnetGroup 'MyRDSDBSubnetGroup',
  Properties:
    DBSubnetGroupDescription: "Subnets available for the RDS DB Instance"
    SubnetIds: [ @Params.SubnetId ]

Thank you,

-Sithu

**Comment by sithu** [comment]
Pulled the latest update and that fixed the issue.
